services:

    postgres:
        build:
            context: ./Docker/postgres
            dockerfile: Dockerfile
        ports: 
            - 5432:5432
        env_file: ./env.env
        restart: always


    pgadmin:
        build: 
            context: ./Docker/pgadmin
            dockerfile: Dockerfile
        ports:
            - 5050:80
        restart: always
        links: 
            - postgres
        env_file: ./env.env
        depends_on:
            - postgres

    
    web:
        build:
            context: ./Docker/bunker_proj
            dockerfile: Dockerfile
        ports: 
            - 8000:8000
        links:
            - postgres
        depends_on:
            - postgres
        restart: always
        env_file: ./env.env
        volumes:
            - ./Docker/bunker_proj/:/usr/src/app/

    game_ms:
        build:
            context: ./Docker/game_ms
            dockerfile: Dockerfile
        ports:
            - 8001:8001
        links:
            - postgres
        depends_on:
            - postgres
        restart: always
        env_file: ./env.env
        volumes:
            - ./Docker/game_ms/:/usr/src/app/

    nginx:
        build:
            context: ./Docker/nginx/
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./Docker/bunker_proj/bunker_proj/static/:/static/
            - ./Docker/bunker_proj/bunker_proj/media/:/media/
            - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        links:
            - postgres
            - pgadmin 
            - web
            - game_ms
        depends_on:
            - postgres
            - pgadmin 
            - web
            - game_ms
        restart: always